name: ClashX.Sing-Box Build

on:
  push:
    tags: [ v* ]
  workflow_dispatch:
    inputs:
      logLevel:

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-10.15

    steps:
      - name: Checkout
        run: |
          git clone https://github.com/mrFq1/ClashX.Sing-Box
          cd ClashX.Sing-Box
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
  
          
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
